### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ziyad-aljohani** [berkkan22/pubspec-dependency-inspector#1]
Thank you for this great and important idea

<img width="527" alt="image" src="https://github.com/berkkan22/pubspec-dependency-inspector/assets/135967503/4dde9049-78a7-4cee-9262-27ca6b2c0823">

it has problem with versions that have (+) 

also why it remove (^) from version number?

**Comment by ziyad-aljohani** [comment]
also it analyze the pubspec.lock file, it should't do that.

**Comment by ziyad-aljohani** [comment]
<img width="732" alt="image" src="https://github.com/berkkan22/pubspec-dependency-inspector/assets/135967503/d66210f0-cf3d-4ba2-8b66-0d7d921af14f">

fix this by limiting to only 1 analyze per time

**Comment by berkkan22** [comment]
Yes, those are indeed valid issues, and I appreciate you bringing them to my attention. I will resolve the issues as soon as possible.

**Comment by ziyad-aljohani** [comment]
@berkkan22 Thank you. it's a very helpful extension.

**Comment by berkkan22** [comment]
I have fixed the issues and published a new version 0.0.3. It should be up in a couple of minutes. If there is still a problem or another problem or feature request let me know.

Thanks for using my extension 😊

**Comment by ziyad-aljohani** [comment]
@berkkan22 wow, everything fixed! Thank you so much!
