### ISSUE TITLE
Keeps listing problems no matter how many times I Fix them

### ISSUE THREAD

**Issue by sgjohnson1981** [berkkan22/pubspec-dependency-inspector#3]
Extension has taken to telling me to update to a version that's already listed no matter how many times I "Fix" it.
![image](https://github.com/berkkan22/pubspec-dependency-inspector/assets/49596637/787b7ec7-4cda-4a79-b39c-4fa118c04129)

**Comment by berkkan22** [comment]
Hi @sgjohnson1981, yeah you're right that should not happen. I will try to fix that asap.

**Comment by berkkan22** [comment]
Hi @sgjohnson1981, I am really sorry I was busy with the university this semester was a bit intense. My apologies.
I am currently trying to reproduce the bug on my side but I can't reproduce it.
Do you still have the bug?
